security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            entity:
                class: App\Entity\Membres
                property: email

    encoders:
        App\Entity\Membres: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: user_provider
            form_login:
                post_only: true
                login_path: landing
                check_path: landing
                use_referer: false
                remember_me: false
                username_parameter: email
                # default_target_path: /profil
                default_target_path: /list
                password_parameter: password
                require_previous_session: false
                always_use_default_target_path: false


            logout:
                target: /
                path: /logout
                success_handler: ~
                invalidate_session: true

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/test/secret, roles: ROLE_USER }
        # - { path: ^/test/profil, roles: ROLE_USER }
        # - { path: ^/test/admin, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/test/secret, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

