security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
            entity:
                class: App\Entity\Membres
                property: email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: user_provider
            form_login:
                post_only: true
                login_path: test_login
                check_path: test_login
                use_referer: false
                remember_me: false
                username_parameter: login[email]
                default_target_path: /home
                password_parameter: login[password]

            logout:
                target: /tests
                path: /testlogout
                success_handler: ~
                invalidate_session: true

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/test/secret, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
