#index:
#    path: /
#    controller: App\Controller\DefaultController::index

landing:
    path: /
    controller: App\Controller\LandingController::landing 

landing_inscript:
    path: /landing_inscript
    controller: App\Controller\LandingController::landing_inscript

logout:
    path: /logout
    controller: App\Controller\LandingController::logout

logout_admin:
    path: /logout_admin
    controller: App\Controller\AdminController::logout_admin

membre_list:
    path: /list
    controller: App\Controller\MembresController::listMembres

membre_show:
    path: /show/{id}
    controller: App\Controller\MembresController::profilShow

prive_profil_own:
    path: /profil
    controller: App\Controller\MembresController::profilShow


prive_profil:
    path: /profil/{id}
    controller: App\Controller\MembresController::profilEdit

prive_messagerie:
    path: /messagerie
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: prive/messagerie.html.twig

admin_config:
    path: /config
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/config.html.twig

admin_membres:
    path: /membres
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/membres.html.twig

admin3_test:
    path: /admin3/test
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin3/testadmin3.html.twig

admin3_index:
    path: /admin3
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin3/admin.html.twig

admin3_users_management:
    path: /admin3/users_management
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/users_management.html.twig  

admin3_permissions:
    path: /admin3/permissions
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/permissions.html.twig  

admin3_moderation:
    path: /admin3/moderation
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/moderation.html.twig  

admin3_send_mailing:
    path: /admin3/send_mailing
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/send_mailing.html.twig  

admin3_private_messages:
    path: /admin3/private_messages
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/private_messages.html.twig  

admin3_admin_mails:
    path: /admin3/admin_mail
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/admin_mail.html.twig  

admin3_admin_tasks:
    path: /admin3/admin_tasks
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin3/admin_tasks.html.twig  




###########################################

       
admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/admin.html.twig


Users_management:
    path: /Users_management
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/Users_management.html.twig   

permissions:
    path: /permissions
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/permissions.html.twig

moderation:
    path: /moderation
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/moderation.html.twig 
        
send_mailing:
    path: /send_mailing
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/send_mailing.html.twig  

private_messages:
    path: /private_messages
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/private_messages.html.twig 

admin_mail:
    path: /admin_mail
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/admin_mail.html.twig
        
admin_tasks:
    path: /admin_tasks
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: /admin2/admin_tasks.html.twig         



########################### TESTS

tests:
    path: /tests
    controller: App\Controller\MembresController::testList 

test_list:
    path: /test/list
    controller: App\Controller\MembresController::testList 

test_show:
    path: /test/show/{id}
    controller: App\Controller\MembresController::testShow 

test_new:
    path: /test/new
    controller: App\Controller\MembresController::testNew 

test_edit:
    path: /test/edit/{id}
    controller: App\Controller\MembresController::testEdit 

test_edit_presentation:
    path: /test/editpresentation/{id}
    controller: App\Controller\MembresController::testEditPresentation 

test_delete:
    path: /test/delete/{id}
    controller: App\Controller\MembresController::testDelete 

test_newmessage:
    path: /test/newmessage/{id}
    controller: App\Controller\MessagerieController::testNew 

test_showmessage:
    path: /test/showmessage/{id}
    controller: App\Controller\MessagesController::testShow 

test_all_messages: 
    path: /test/messages 
    controller: App\Controller\MessagesController::testAllMessagerie 

test_messagerie:
    path: /test/profil/messagerie
    controller: App\Controller\MessagesController::testMessagerie 

test_login:
    path: /test/login
    controller: App\Controller\MembresController::testLogin 
    
test_logout:
    path: /test/logout
    controller: App\Controller\MembresController::testLogout 
    
test_secret:
    path: /test/secret
    controller:  Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: tests/secret.html.twig
