#index:
#    path: /
#    controller: App\Controller\DefaultController::index

membre_list:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/index.html.twig

membre_show:
    path: /show
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/show.html.twig

