#index:
#    path: /
#    controller: App\Controller\DefaultController::index

landing:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/landing.html.twig

landing_inscript:
    path: /landing_inscript
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/landing_inscript.html.twig

membre_list:
    path: /list
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/list.html.twig

membre_show:
    path: /show
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/show.html.twig

prive_profil:
    path: /profil
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: prive/profil.html.twig

prive_messagerie:
    path: /messagerie
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: prive/messagerie.html.twig

admin_config:
    path: /config
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/config.html.twig

admin_membres:
    path: /membres
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: admin/membres.html.twig